// Generated by gencpp from file jw/projectMsg.msg
// DO NOT EDIT!


#ifndef JW_MESSAGE_PROJECTMSG_H
#define JW_MESSAGE_PROJECTMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jw
{
template <class ContainerAllocator>
struct projectMsg_
{
  typedef projectMsg_<ContainerAllocator> Type;

  projectMsg_()
    : Direction(0)
    , Move(0)
    , Done(0)  {
    }
  projectMsg_(const ContainerAllocator& _alloc)
    : Direction(0)
    , Move(0)
    , Done(0)  {
  (void)_alloc;
    }



   typedef int32_t _Direction_type;
  _Direction_type Direction;

   typedef int32_t _Move_type;
  _Move_type Move;

   typedef int32_t _Done_type;
  _Done_type Done;





  typedef boost::shared_ptr< ::jw::projectMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jw::projectMsg_<ContainerAllocator> const> ConstPtr;

}; // struct projectMsg_

typedef ::jw::projectMsg_<std::allocator<void> > projectMsg;

typedef boost::shared_ptr< ::jw::projectMsg > projectMsgPtr;
typedef boost::shared_ptr< ::jw::projectMsg const> projectMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jw::projectMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jw::projectMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace jw

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'jw': ['/home/jw/catkin_ws/src/jw/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::jw::projectMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jw::projectMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jw::projectMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jw::projectMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jw::projectMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jw::projectMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jw::projectMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d6f9748fb09b67c96badc84c2aee66af";
  }

  static const char* value(const ::jw::projectMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd6f9748fb09b67c9ULL;
  static const uint64_t static_value2 = 0x6badc84c2aee66afULL;
};

template<class ContainerAllocator>
struct DataType< ::jw::projectMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jw/projectMsg";
  }

  static const char* value(const ::jw::projectMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jw::projectMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 Direction\n\
int32 Move\n\
int32 Done\n\
";
  }

  static const char* value(const ::jw::projectMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jw::projectMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Direction);
      stream.next(m.Move);
      stream.next(m.Done);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct projectMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jw::projectMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jw::projectMsg_<ContainerAllocator>& v)
  {
    s << indent << "Direction: ";
    Printer<int32_t>::stream(s, indent + "  ", v.Direction);
    s << indent << "Move: ";
    Printer<int32_t>::stream(s, indent + "  ", v.Move);
    s << indent << "Done: ";
    Printer<int32_t>::stream(s, indent + "  ", v.Done);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JW_MESSAGE_PROJECTMSG_H
